In [1]:
import numpy as  np

In [2]:
# implement numpy array and its attributes
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
a = np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
print(arr.ndim)  # number of dimensions
print(arr.shape) # shape of the array
print(arr.size)  # total number of elements
print(arr.dtype) # data type of elements

1
(5,)
5
int64


In [8]:
# 2d numpy array
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.dtype)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [11]:
# make array using zeros and ones
arr_zeros = np.zeros((3,4))
print(arr_zeros)
print(arr_zeros.dtype)
arr_ones = np.ones((2,3))
print(arr_ones)

# chnange data type
arr_3 = np.zeros((2,3), dtype = 'int32')
print(arr_3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [13]:
# arange , linespace, logspace, eye, identity, diag, random, empty, full
arr_arange = np.arange(0,10,2)
print(arr_arange)
arr_linspace = np.linspace(0,13,5, dtype = 'int32')
print(arr_linspace)
arr_logspace = np.logspace(0,3,4)
print(arr_logspace)
arr_eye = np.eye(3)
print(arr_eye)
arr_identity = np.identity(4)
print(arr_identity)
arr_diag = np.diag([1,2,3,4])
print(arr_diag)
arr_random = np.random.rand(3,4)
print(arr_random)
arr_empty = np.empty((2,3))
print(arr_empty)
arr_full = np.full((2,3),7)
print(arr_full)

[0 2 4 6 8]
[ 0  3  6  9 13]
[   1.   10.  100. 1000.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0.10705436 0.17464018 0.31646677 0.39959916]
 [0.74113126 0.5053283  0.60666565 0.94156914]
 [0.6422178  0.59169309 0.78023788 0.12409127]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


In [16]:
# Mathematical opeeation on numpty arrays
b = np.array([10,20,30,40,50])
print(b[2]+b[4])

print(arr+b)  # element wise addition
print(arr-b)  # element wise subtraction
print(arr*b)  # element wise multiplication
print(b%arr)  # element wise division

80
[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0 0 0 0 0]


In [18]:
print(b.astype('float64'))  # change data type

[10. 20. 30. 40. 50.]


In [19]:
c = np.array([0,2,0,1,0,0,5,3,7])
print(np.nonzero(c))  # index of non zero elements
print(c.astype('bool'))  # change to boolean array

(array([1, 3, 6, 7, 8]),)
[False  True False  True False False  True  True  True]


In [21]:
# difference between copy and view : copy creates a new array and view creates a view of the original array and if we change the view the original array will also change but if we change the copy the original array will not change

c = arr.copy()
d = arr.view()
print(c)
print(d)

# chnge in view  and copy
d[0] = 100
print(arr)
print(d)
c[3] = 200
print(arr)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[100   2   3   4   5]
[  1   2   3 200   5]


In [ ]:
# series: 1d array
s = np.array([1,2,3,4,5])
print(s

[1 2 3 4 5]


In [28]:
import pandas as pd
w = [1,2,3,4,5]
myvar = pd.Series(w, index = ['a','b','c','d','e'])
print(myvar)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [29]:
# function that used in Series
print(myvar.index)
print(myvar.dtype)


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
int64


In [4]:
# data frames
data =  {'calories': [420, 380, 390],
         'duration': [50, 40, 45],
         'name': ['A', 'B', 'C'],
         'age': [21, 22, 23],
         'city': ['Delhi', 'Noida', 'Gurgaon'],
         }
df = pd.DataFrame(data)
print(df)

NameError: name 'pd' is not defined

In [2]:
# load csv file
df2 = pd.read_csv('data.csv')
print(df2)

NameError: name 'pd' is not defined

In [3]:
df2.isnull()  # check for null values

NameError: name 'df2' is not defined

In [35]:
df.isnull().sum()  # sum of null values in each column

calories    0
duration    0
name        0
age         0
city        0
dtype: int64

In [37]:
# check duplicate values
df.duplicated()

df.drop_duplicates(inplace = True)  # drop duplicate values
print(df)


   calories  duration name  age     city
0       420        50    A   21    Delhi
1       380        40    B   22    Noida
2       390        45    C   23  Gurgaon


In [1]:
# count duplicate valuee
df.duplicated().sum

NameError: name 'df' is not defined